name: "tagged-release"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  tagged-release:
    name: "Release Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Build native"
        run: make build
        working-directory: "."

      - name: Setup System
        run: sudo wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf && sudo chmod +x /usr/bin/ape && sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register" && sudo sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

      - name: "Build for all"
        run: make setup-cosmocc && make build CC=./cosmocc/bin/cosmocc ARCH=all
        working-directory: "."

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag" \
              --generate-notes

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "$tag" \
            ./cerve_${{ github.ref_name }}_x86_64 \
            ./cerve_${{ github.ref_name }}_all \
            ./cerve_${{ github.ref_name }}_all.aarch64.elf \
            ./cerve_${{ github.ref_name }}_all.com.dbg
        working-directory: "."
